[build]
  command = "npm run build"
  publish = "dist"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Handle SPA routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pdf-lib", "tesseract.js"]

[functions."kv-extract"]
  included_files = ["dist/**"]

[functions."ocr-paddle"]
  included_files = ["dist/**"]

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"