[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"